### ISSUE TITLE
Opening the aerobic model provided in the supp. results in exception during loading

### ISSUE THREAD

**Issue by Unaimend** [cbrinkrolf/VANESA#10]
Hello, I just wanted to try this application but sadly when loading the aerobic model.
VANESA gets stuck [1]
and an exception is throw [2]. Do you have any idea how to fix this 
[1] ![image](https://github.com/user-attachments/assets/75d3dda8-e6b3-48a9-b8af-c92facffaea9)

[2] `org.jdom2.JDOMException: Unable to create SAX2 XMLReader.
	at org.jdom2.input.sax.XMLReaderSAX2Factory.createXMLReader(XMLReaderSAX2Factory.java:129)
	at org.jdom2.input.SAXBuilder.createParser(SAXBuilder.java:874)
	at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:857)
	at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:907)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1053)
	at util.VanesaUtility.loadXmlDocument(VanesaUtility.java:113)
	at io.sbml.JSBMLInput.loadSBMLFile(JSBMLInput.java:52)
	at io.OpenDialog.openSBML(OpenDialog.java:86)
	at io.OpenDialog.open(OpenDialog.java:55)
	at io.OpenDialog.lambda$show$0(OpenDialog.java:44)
	at gui.AsyncTaskExecutor.lambda$runUIBlocking$0(AsyncTaskExecutor.java:9)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.xml/org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:200)
	at java.xml/org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
	at org.jdom2.input.sax.XMLReaderSAX2Factory.createXMLReader(XMLReaderSAX2Factory.java:118)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at java.xml/org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:91)
	at java.xml/org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:198)
	... 19 more
`

**Comment by cbrinkrolf** [comment]
Hey,
it looks like there is an issue with the XML parser that I cannot reproduce using my IDE right now. Which JRE/JDK/Java version are you using? As an alternative, you might like to try to use the (latest) pre-compiled jars provided as releases here on GitHub. 

In general, is the aerobic model you tried to load the sbml file from the suppl. material of the publication [1]?

I am looking forward hearing your feedback. There will be also a new (pre)-release within the next 1-2 weeks.

[1] https://doi.org/10.1515/jib-2018-0018

**Comment by Unaimend** [comment]
Thank you for your response.

The model in aerobic  model in question is indeed the one linked by you in [1].
My local java version is java 11, which at least to the README.txt provided in the supplementary of [1] is sufficient.
![image](https://github.com/user-attachments/assets/589efde8-2ce1-4297-9e32-48d4383d5f40)

I also tested the pre-compiled version and was indeed able to open the program. Thank you very much for this suggestion. If you still need information about the issues with the locally built version, I'm happy to assist.

**Comment by cbrinkrolf** [comment]
Thank you for your effort. Indeed, Java 11 is sufficient but something goes wrong with the JDOM library. We are planning to get rid of that library and it would be interesting to see if that error then still might occur. Thus, I will keep this issue open and I will report here once we made those adaptions. Thanks in advance for your assistance!
